//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMobileAppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRQuestion
    {
        public int ID { get; set; }
        public Nullable<int> TechCategoryID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual TechCategory TechCategory { get; set; }
    }
}
